[book]
authors = ["fifth_light"]
title = "TouchController-Monorepo"
language = "cmn-hans-cn"

[output.html]
git-repository-url = "https://github.com/TouchController/TouchController-Monorepo/tree/master/touchcontroller/doc"
