license="${license}"
issueTrackerURL="${issue_tracker}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${name}"
displayURL="${home_page}"
logoFile="assets/blazerod/icon.png"
authors="fifth_light"
description='''${description}'''
