name: Build Mod
on: [pull_request, push]

jobs:
    build-mod:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
                with:
                    submodules: 'true'

            -   name: Install Bazelisk
                run: |
                    curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.19.0/bazelisk-linux-amd64"
                    chmod +x bazelisk-linux-amd64
                    sudo mv bazelisk-linux-amd64 /usr/local/bin/bazel

            -   name: Build TouchController Mod
                run: |
                    bazel build //touchcontroller/...

            -   name: Capture Mod Artifacts
                uses: actions/upload-artifact@v4
                with:
                    name: mod-artifacts
                    compression-level: 9
                    if-no-files-found: error
                    path: |
                        bazel-bin/touchcontroller/**/*.jar

    build-mod-release:
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
                with:
                    submodules: 'true'

            -   name: Install Bazelisk
                run: |
                    curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.19.0/bazelisk-linux-amd64"
                    chmod +x bazelisk-linux-amd64
                    sudo mv bazelisk-linux-amd64 /usr/local/bin/bazel

            -   name: Build TouchController Mod
                run: |
                    bazel build //touchcontroller/...

            -   name: Create Release
                uses: softprops/action-gh-release@v2
                with:
                    files: bazel-bin/touchcontroller/**/*.jar
                    generate_release_notes: true
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}